export const PRIMARYORANGECOLOR = '#FF9900'

export const NEUTRALGREYCOLOR = '#EEEEEE'

export const SOLIDWHITECOLOR = '#FFFFFF'

export const SOLIDBLACKCOLOR = '#000000'

export const VARIANTBLUE = '#34495E'

export const VARIANTDARKPURPLE = '#741B47'